### PR TITLE
Add Red Hat Inc AMIs

### PR DESCRIPTION
**Pull request by zkayyali812**
Extension Node 100 - https://us-east-1.console.aws.amazon.com/marketplace/home?region=us-east-1#/subscriptions/ba81c1e5-a4dc-4b63-a7c4-4dc8a0865ba1
Extension Node 200 - https://us-east-1.console.aws.amazon.com/marketplace/home?region=us-east-1#/subscriptions/4a9585d1-e781-42b9-9b41-23e8b6398a7b
Extension Node 400 - https://us-east-1.console.aws.amazon.com/marketplace/home?region=us-east-1#/subscriptions/bf817b5b-d2a6-4bb8-945e-78f0465f5e50

To validate the AMIs - 
1. Click one of the links above
2. Click `Lauch new instance`
3. Use the `Region` drop down to double check the AMI ID for each region

This PR only onboards the Red Hat Inc extension node AMIs.
Once we get the Red Hat Limited foundation AMIs, those will be added in a separate PR.

### CODE REVIEW

**Comment by chrisahl** [comment]
Looking at Ext 100, I see 
image
in Launch new instance but we don't have entries for il-central-1

**Comment by zkayyali812** [comment]
@chrisahl Great catch!
I noticed this too, but I did not add this in, due to our foundation offerings not having this region available to them yet, so I purposefully did not include this region.
Once our foundation supports it, I expect we can also add this in.

**Comment by chrisahl** [comment]
Ext 200 has same il-central-1 issue but all other values match.   Would be nice if all the values in the file were sorted the same as UI.  A few are out of order

**Review by chrisahl — APPROVED** [review]
That was a lot of manual checking!

**Review by prat98 — APPROVED** [review]
Manually checked all the AMIs for the extensions as well. Everything matches for 100, 200 and 400. Also saw that extra region `il-central-1` but otherwise everything matches. LGTM!

**Pull request merged**
